# Generated by Django 2.1.7 on 2019-04-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vot_total',
            new_name='votes_total',
        ),
    ]
